# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "Cloud-W0-example1"
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.linked_clone = true
  end

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.44.10"

  config.vm.synced_folder "../img", "/vagrant_ipt"
end
